version: "3.3"
services:
  certificate-dashboard:
    environment:
     - MONITORED_CERT_HOSTS=
     - DAYS_LEFT_DANGER=10
     - DAYS_LEFT_WARNING=20
     - CONNECTION_TIMEOUT=5000
    image: dash
    ports:
      - 5000:5000/tcp